services:
  lineoa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LIFF_ID=${LIFF_ID}
        - SCHOOL_NAME=${SCHOOL_NAME}
    container_name: titita-lineoa
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MOCK_MODE=false
      - MONGODB_URI=${MONGODB_URI}
      - MAIN_SYSTEM_URL=http://titita-onecloud:3000 # Docker 內部網路用 container name
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - LINE_CHANNEL_ID=${LINE_CHANNEL_ID}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LIFF_ID=${LIFF_ID}
      - SCHOOL_NAME=${SCHOOL_NAME}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
    networks:
      - titita-network


networks:
  titita-network:
    external: true
