services:
  lineoa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LIFF_ID=${LIFF_ID}
        - SCHOOL_NAME=${SCHOOL_NAME}
    container_name: titita-lineoa
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    environment:
      - MOCK_MODE=false
    networks:
      - titita_onecloud


networks:
  titita_onecloud:
    external: true
